steps:
  # 1. Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/tracking-repo/tracking-api'
      - '.'

  # 2. Push da imagem
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/tracking-repo/tracking-api'

  # 3. Deploy no Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - tracking-api
      - --image
      - southamerica-east1-docker.pkg.dev/$PROJECT_ID/tracking-repo/tracking-api
      - --region
      - southamerica-east1
      - --platform
      - managed
      - --allow-unauthenticated
      - --update-secrets
      - SECRET_KEY=tracking-api-secret-key:latest

images:
  - southamerica-east1-docker.pkg.dev/$PROJECT_ID/tracking-repo/tracking-api

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET